name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.18.1"
          registry-url: "https://npm.pkg.github.com"
          scope: "@digital-swing"      
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.gsap.npmRegistryServer "https://npm.greensock.com"
          yarn config set npmScopes.gsap.npmAlwaysAuth true
          yarn config set npmScopes.gsap.npmAuthToken $GSAP_TOKEN
      - run: yarn
      - run: yarn build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn test --passWithNoTests
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}