on:
  push:
    branches:
      - main
name: Update release PR / Create release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@digital-swing"      
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.gsap.npmRegistryServer "https://npm.greensock.com"
          yarn config set npmScopes.gsap.npmAlwaysAuth true
          yarn config set npmScopes.gsap.npmAuthToken $GSAP_TOKEN
      - run: yarn
      - run: yarn build
      - run: yarn publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}