on:
  push:
    branches:
      - main
name: Update release PR / Create release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Setup .yarnrc.yml
        if: ${{ steps.release.outputs.release_created }}
        run: |
          yarn config set npmScopes.gsap.npmRegistryServer "https://npm.greensock.com"
          yarn config set npmScopes.gsap.npmAlwaysAuth true
          yarn config set npmScopes.gsap.npmAuthToken $GSAP_TOKEN
      - run: yarn install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn build
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
